### ISSUE TITLE
new version for mercurius v12?

### ISSUE THREAD

**Issue by trim21** [PabloSzx/mercurius-integration-testing#12]
> warning " > mercurius-integration-testing@6.0.1" has incorrect peer dependency "mercurius@^11.0.0".

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by trim21** [comment]
create a new npm project, install `mercurius` v12 and latest `mercurius-integration-testing` version

**Comment by mcollina** [comment]
Ah great!! This needs work.

**Comment by trim21** [comment]
currently npm resolution error

```text
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: mercurius-integration-testing@6.0.1
npm ERR! Found: mercurius@12.1.0
npm ERR! node_modules/mercurius
npm ERR!   mercurius@"^12.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mercurius@"^11.0.0" from mercurius-integration-testing@6.0.1
npm ERR! node_modules/mercurius-integration-testing
npm ERR!   dev mercurius-integration-testing@"^6.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: mercurius@11.5.0
npm ERR! node_modules/mercurius
npm ERR!   peer mercurius@"^11.0.0" from mercurius-integration-testing@6.0.1
npm ERR!   node_modules/mercurius-integration-testing
npm ERR!     dev mercurius-integration-testing@"^6.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by trim21** [comment]
> Would you like to send a PR?

checkout https://github.com/mercurius-js/mercurius-integration-testing/pull/13 please
