### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by rodlukas** [PabloSzx/mercurius-integration-testing#23]
Could you please publish new version of the mercurius-integration-testing package to npm so it allows mercurius 14 as peer dependency? 
Thanks :)

**Comment by fabulator** [comment]
@mcollina could you make a release to npm, please? We cannot bump mercurius version because this package depends on an old version.

**Comment by PabloSzx** [comment]
https://github.com/mercurius-js/mercurius-integration-testing/releases/tag/v8.2.0

published 8.2.0
